"""WorkflowEngine: orchestrates workflow state transitions in reaction to events.

Part 1 scope was the state machine logic hooked to the event bus via
placeholder handlers that just logged + transitioned state. Part 2 replaces
those placeholder handlers with real agent invocations (registered via
backend.events.registry from backend/agents/wiring.py) and adds three
pieces the agent layer needs that Part 1 didn't have yet:

  1. ``submit_user_goal`` -- the front door. Part 1 only exposed
     ``create_workflow`` (called directly, synchronously). Part 2 needs an
     entry point that takes a raw goal string and kicks off the event chain
     *before* a Workflow row exists (GoalInterpreterAgent, RegulationAgent
     and WorkflowPlannerAgent all run before the graph is known). This
     generates the workflow_id up front and publishes USER_REQUEST_CREATED;
     every downstream event shares that same workflow_id.
  2. ``create_workflow_from_steps`` -- WorkflowPlannerAgent derives a
     dynamic list of WorkflowStep objects (via Gemini + RAG) instead of
     always using the hardcoded template. This shares creation logic with
     the original template-based ``create_workflow`` and accepts the
     workflow_id generated by ``submit_user_goal`` so the id stays stable
     across the whole event chain.
  3. ``block_step`` / ``resume_step`` -- the human-in-the-loop gate.
     Part 1's placeholder handler hard-*failed* a step (and the whole
     workflow) on APPLICATION_REJECTED. Part 2 needs rejection/ineligibility
     to be a *recoverable* gate (WorkflowStatus.BLOCKED /
     StepStatus.BLOCKED) that a future WORKFLOW_RESUMED event (Part 3 will
     expose this as a "resume" API route) can unblock, rather than an
     irreversible WORKFLOW_FAILED. Routine transitions (submit, poll,
     retry, approve) do NOT go through this gate -- only genuinely
     risky/uncertain ones do.
"""

from __future__ import annotations

import asyncio
import logging
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from backend.events.bus import EventBus
from backend.events.registry import register_handler
from backend.models.enums import EventType, StepStatus, WorkflowStatus
from backend.models.event import Event
from backend.models.workflow import Workflow, WorkflowStep
from backend.services.interfaces import AuditRepository, EventRepository, WorkflowRepository
from backend.workflows.graph import WorkflowGraph
from backend.workflows.templates import FOOD_PROCESSING_BUSINESS_TEMPLATE, get_template

logger = logging.getLogger("govflow.workflows.engine")


class WorkflowEngine:
    def __init__(
        self,
        event_bus: EventBus,
        workflow_repo: WorkflowRepository,
        event_repo: EventRepository,
        audit_repo: Optional[AuditRepository] = None,
    ) -> None:
        self.event_bus = event_bus
        self.workflow_repo = workflow_repo
        self.event_repo = event_repo
        self.audit_repo = audit_repo
        self._graphs: Dict[str, WorkflowGraph] = {}

    # ------------------------------------------------------------------
    # Graph access
    # ------------------------------------------------------------------

    def get_graph(self, workflow_id: str) -> WorkflowGraph:
        if workflow_id not in self._graphs:
            raise KeyError(
                f"no in-memory graph for workflow_id={workflow_id!r}. "
                "Graphs are only available for workflows created in this process "
                "(Part 1 limitation -- graphs do not survive a process restart)."
            )
        return self._graphs[workflow_id]

    def has_graph(self, workflow_id: str) -> bool:
        return workflow_id in self._graphs

    # ------------------------------------------------------------------
    # Front door (Part 2)
    # ------------------------------------------------------------------

    async def submit_user_goal(
        self, user_id: str, goal: str, metadata: Optional[Dict[str, Any]] = None
    ) -> str:
        """Generates a workflow_id and publishes USER_REQUEST_CREATED.

        No Workflow row exists yet at this point -- GoalInterpreterAgent,
        RegulationAgent and WorkflowPlannerAgent run first and
        ``create_workflow_from_steps`` is what actually persists the row,
        using this same workflow_id.

        AWAITS the full synchronous cascade (InProcessEventBus.publish()
        awaits every handler before returning, and that nests all the way
        through the agent chain up to the first point that schedules a
        background task -- StatusMonitorAgent's polling). Fine for
        scripts/tests that want to await full completion; an HTTP request
        handler that must respond immediately should use
        ``start_user_goal_async`` instead (Part 3).

        ``metadata`` is threaded through GOAL_ANALYZED and onto the
        persisted Workflow (see WorkflowPlannerAgent) -- primarily used by
        the Part 3 demo orchestrator to force a deterministic mock-API
        scenario regardless of Gemini's free-form extraction.
        """
        workflow_id = str(uuid.uuid4())
        event = Event(
            workflow_id=workflow_id,
            event_type=EventType.USER_REQUEST_CREATED,
            payload={"goal": goal, "user_id": user_id, "metadata": metadata or {}},
            source_agent="workflow_engine",
        )
        await self._record_and_publish(event)
        return workflow_id

    def start_user_goal_async(
        self, user_id: str, goal: str, metadata: Optional[Dict[str, Any]] = None
    ) -> str:
        """Fire-and-forget variant of ``submit_user_goal`` for API callers.

        Added in Part 3: an HTTP route must return a response immediately
        (per the spec: "do NOT block waiting for the agent chain to
        finish"), but ``submit_user_goal`` awaits the entire synchronous
        cascade before returning the workflow_id -- with a real Gemini
        client that can be several seconds (3 sequential LLM calls before
        the first background poll task is scheduled). This generates the
        workflow_id synchronously, schedules the actual publish as a
        background asyncio task, and returns immediately. The workflow_id
        is usable right away for WebSocket subscription; GET
        /api/workflows/{id} may briefly 404 until WorkflowPlannerAgent
        creates the row.
        """
        workflow_id = str(uuid.uuid4())
        asyncio.create_task(self._publish_user_request(workflow_id, user_id, goal, metadata))
        return workflow_id

    async def _publish_user_request(
        self, workflow_id: str, user_id: str, goal: str, metadata: Optional[Dict[str, Any]]
    ) -> None:
        event = Event(
            workflow_id=workflow_id,
            event_type=EventType.USER_REQUEST_CREATED,
            payload={"goal": goal, "user_id": user_id, "metadata": metadata or {}},
            source_agent="workflow_engine",
        )
        await self._record_and_publish(event)

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    async def create_workflow(
        self,
        user_id: str,
        goal: str,
        template_name: str = FOOD_PROCESSING_BUSINESS_TEMPLATE,
        workflow_id: Optional[str] = None,
    ) -> Workflow:
        """Creates a workflow from the hardcoded demo template (Part 1 path)."""
        steps = get_template(template_name)
        return await self._create_workflow_with_steps(
            user_id=user_id, goal=goal, steps=steps, template_name=template_name, workflow_id=workflow_id
        )

    async def create_workflow_from_steps(
        self,
        user_id: str,
        goal: str,
        steps: List[WorkflowStep],
        workflow_id: Optional[str] = None,
        template_name: str = "dynamic",
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Workflow:
        """Creates a workflow from a dynamically-planned step list (Part 2 path).

        Used by WorkflowPlannerAgent once it has derived the required
        services + dependency edges via Gemini + RAG results, instead of
        the hardcoded template.
        """
        return await self._create_workflow_with_steps(
            user_id=user_id,
            goal=goal,
            steps=steps,
            template_name=template_name,
            workflow_id=workflow_id,
            metadata=metadata,
        )

    async def _create_workflow_with_steps(
        self,
        *,
        user_id: str,
        goal: str,
        steps: List[WorkflowStep],
        template_name: str,
        workflow_id: Optional[str],
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Workflow:
        workflow_id = workflow_id or str(uuid.uuid4())
        graph = WorkflowGraph(steps)
        self._graphs[workflow_id] = graph

        workflow = Workflow(
            workflow_id=workflow_id,
            user_id=user_id,
            goal=goal,
            status=WorkflowStatus.RUNNING,
            pending_steps=graph.pending_step_ids(),
            metadata=metadata or {},
        )
        self.workflow_repo.create(workflow)

        event = Event(
            workflow_id=workflow_id,
            event_type=EventType.WORKFLOW_CREATED,
            payload={"template": template_name, "goal": goal, "step_ids": [s.id for s in steps]},
            source_agent="workflow_engine",
        )
        await self._record_and_publish(event)

        claimed = graph.claim_ready_steps()
        workflow = self._sync_workflow_from_graph(workflow_id)
        if claimed:
            await self._record_and_publish(
                Event(
                    workflow_id=workflow_id,
                    event_type=EventType.NEXT_ACTION_TRIGGERED,
                    payload={"ready_steps": [s.id for s in claimed]},
                    source_agent="workflow_engine",
                )
            )
        return workflow

    async def complete_step(self, workflow_id: str, step_id: str) -> Workflow:
        graph = self.get_graph(workflow_id)
        graph.mark_step_status(step_id, StepStatus.COMPLETED)
        logger.info("workflow=%s step=%s -> COMPLETED", workflow_id, step_id)

        claimed = graph.claim_ready_steps()
        workflow = self._sync_workflow_from_graph(workflow_id)

        if graph.is_complete():
            await self._record_and_publish(
                Event(
                    workflow_id=workflow_id,
                    event_type=EventType.WORKFLOW_COMPLETED,
                    payload={"completed_steps": graph.completed_step_ids()},
                    source_agent="workflow_engine",
                )
            )
        elif claimed:
            await self._record_and_publish(
                Event(
                    workflow_id=workflow_id,
                    event_type=EventType.NEXT_ACTION_TRIGGERED,
                    payload={"ready_steps": [s.id for s in claimed]},
                    source_agent="workflow_engine",
                )
            )
        return workflow

    async def fail_step(self, workflow_id: str, step_id: str, reason: str) -> Workflow:
        """Permanently fails a step and the workflow. Reserved for
        non-recoverable failures (retry exhaustion) -- not for
        rejection/ineligibility, which go through ``block_step`` instead
        since those are recoverable via human review."""
        graph = self.get_graph(workflow_id)
        graph.mark_step_status(step_id, StepStatus.FAILED)
        logger.warning("workflow=%s step=%s -> FAILED (%s)", workflow_id, step_id, reason)

        workflow = self._sync_workflow_from_graph(workflow_id)
        await self._record_and_publish(
            Event(
                workflow_id=workflow_id,
                event_type=EventType.WORKFLOW_FAILED,
                payload={"failed_step": step_id, "reason": reason},
                source_agent="workflow_engine",
            )
        )
        return workflow

    # ------------------------------------------------------------------
    # Human-in-the-loop gate (Part 2)
    # ------------------------------------------------------------------

    async def block_step(
        self,
        workflow_id: str,
        step_id: str,
        reason: str,
        workflow_status: WorkflowStatus = WorkflowStatus.BLOCKED,
    ) -> Workflow:
        """Pauses autonomous progression on a recoverable, risky/uncertain
        transition (application rejected, applicant ineligible). Unlike
        ``fail_step`` this is not terminal -- ``resume_step`` can put the
        step back to PENDING so it becomes ready again."""
        graph = self.get_graph(workflow_id)
        graph.mark_step_status(step_id, StepStatus.BLOCKED)
        logger.warning("workflow=%s step=%s -> BLOCKED (%s)", workflow_id, step_id, reason)

        workflow = self.workflow_repo.get(workflow_id)
        if workflow is None:
            raise KeyError(f"workflow {workflow_id!r} not found in persistence")
        workflow.completed_steps = graph.completed_step_ids()
        workflow.pending_steps = graph.active_step_ids()
        workflow.failed_steps = graph.failed_step_ids()
        workflow.status = workflow_status
        workflow.updated_at = datetime.now(timezone.utc)
        self.workflow_repo.update(workflow)

        await self._record_and_publish(
            Event(
                workflow_id=workflow_id,
                event_type=EventType.USER_ACTION_REQUIRED,
                payload={"step_id": step_id, "reason": reason, "gate": workflow_status.value},
                source_agent="workflow_engine",
            )
        )
        return workflow

    async def block_workflow(
        self,
        workflow_id: str,
        reason: str,
        workflow_status: WorkflowStatus = WorkflowStatus.WAITING_FOR_USER,
    ) -> Workflow:
        """Workflow-level gate not tied to a specific DAG step -- used by
        EligibilityAgent, whose ineligible/needs_information findings apply
        to the whole workflow rather than one step."""
        workflow = self.workflow_repo.get(workflow_id)
        if workflow is None:
            raise KeyError(f"workflow {workflow_id!r} not found in persistence")
        workflow.status = workflow_status
        workflow.updated_at = datetime.now(timezone.utc)
        self.workflow_repo.update(workflow)
        logger.warning("workflow=%s -> %s (%s)", workflow_id, workflow_status.value, reason)

        await self._record_and_publish(
            Event(
                workflow_id=workflow_id,
                event_type=EventType.USER_ACTION_REQUIRED,
                payload={"reason": reason, "gate": workflow_status.value},
                source_agent="workflow_engine",
            )
        )
        return workflow

    async def resume_step(self, workflow_id: str, step_id: str, action: str = "retry") -> Workflow:
        """Reacts to WORKFLOW_RESUMED. action="retry" puts the step back to
        PENDING (so it can become ready again and re-trigger
        NEXT_ACTION_TRIGGERED); action="abandon" fails it permanently."""
        graph = self.get_graph(workflow_id)
        if action == "abandon":
            return await self.fail_step(workflow_id, step_id, reason="abandoned by user after review")

        graph.mark_step_status(step_id, StepStatus.PENDING)
        logger.info("workflow=%s step=%s -> PENDING (resumed, action=%s)", workflow_id, step_id, action)

        claimed = graph.claim_ready_steps()
        workflow = self._sync_workflow_from_graph(workflow_id, force_status=WorkflowStatus.RUNNING)

        if claimed:
            await self._record_and_publish(
                Event(
                    workflow_id=workflow_id,
                    event_type=EventType.NEXT_ACTION_TRIGGERED,
                    payload={"ready_steps": [s.id for s in claimed]},
                    source_agent="workflow_engine",
                )
            )
        return workflow

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    async def _record_and_publish(self, event: Event) -> None:
        self.event_repo.append(event)
        await self.event_bus.publish(event)

    def _sync_workflow_from_graph(
        self, workflow_id: str, force_status: Optional[WorkflowStatus] = None
    ) -> Workflow:
        graph = self._graphs[workflow_id]
        workflow = self.workflow_repo.get(workflow_id)
        if workflow is None:
            raise KeyError(f"workflow {workflow_id!r} not found in persistence")

        workflow.completed_steps = graph.completed_step_ids()
        workflow.pending_steps = graph.active_step_ids()
        workflow.failed_steps = graph.failed_step_ids()

        # current_step prefers a step actually being worked on (RUNNING --
        # i.e. already claimed via claim_ready_steps) over a merely-ready
        # PENDING one, since claim_ready_steps marks steps RUNNING in the
        # same synchronous call that computes them, so by the time this
        # runs there is usually no unclaimed-but-ready step left to report.
        running = [s for s in graph.all_steps() if s.status == StepStatus.RUNNING]
        if running:
            workflow.current_step = running[0].id
        else:
            ready = graph.get_ready_steps()
            workflow.current_step = ready[0].id if ready else None

        if force_status is not None:
            workflow.status = force_status
        elif graph.is_complete():
            workflow.status = WorkflowStatus.COMPLETED
        elif graph.failed_step_ids():
            workflow.status = WorkflowStatus.FAILED
        elif graph.blocked_step_ids():
            workflow.status = WorkflowStatus.BLOCKED
        else:
            workflow.status = WorkflowStatus.RUNNING

        workflow.updated_at = datetime.now(timezone.utc)
        self.workflow_repo.update(workflow)
        return workflow

    # ------------------------------------------------------------------
    # Core deterministic event handlers
    #
    # These are NOT LLM-driven -- they are the engine's own state-machine
    # reactions to semantic events published by agents (StatusMonitorAgent
    # mainly). Kept here (not in an agent) because "deterministic code
    # should decide control flow" per the project's engineering rules: an
    # approval always completes a step, a rejection always opens the HITL
    # gate, regardless of which agent produced the event.
    # ------------------------------------------------------------------

    def register_core_handlers(self) -> None:
        register_handler(EventType.APPLICATION_APPROVED, self._on_application_approved)
        register_handler(EventType.APPLICATION_REJECTED, self._on_application_rejected)
        register_handler(EventType.DOCUMENT_MISSING, self._on_document_missing)
        register_handler(EventType.WORKFLOW_COMPLETED, self._on_workflow_completed)
        register_handler(EventType.WORKFLOW_FAILED, self._on_workflow_failed)
        register_handler(EventType.WORKFLOW_RESUMED, self._on_workflow_resumed)

    async def _on_application_approved(self, event: Event) -> None:
        step_id = event.payload.get("step_id")
        logger.info("APPLICATION_APPROVED workflow=%s step=%s", event.workflow_id, step_id)
        if step_id and self.has_graph(event.workflow_id):
            await self.complete_step(event.workflow_id, step_id)

    async def _on_application_rejected(self, event: Event) -> None:
        step_id = event.payload.get("step_id")
        reason = event.payload.get("reason", "application rejected")
        logger.info("APPLICATION_REJECTED workflow=%s step=%s", event.workflow_id, step_id)
        if step_id and self.has_graph(event.workflow_id):
            await self.block_step(event.workflow_id, step_id, reason=reason, workflow_status=WorkflowStatus.BLOCKED)

    async def _on_document_missing(self, event: Event) -> None:
        logger.info("DOCUMENT_MISSING workflow=%s payload=%s", event.workflow_id, event.payload)
        step_id = event.payload.get("step_id")
        if step_id and self.has_graph(event.workflow_id):
            await self.block_step(
                event.workflow_id,
                step_id,
                reason=event.payload.get("reason", "required documents missing"),
                workflow_status=WorkflowStatus.WAITING_FOR_USER,
            )
        else:
            workflow = self.workflow_repo.get(event.workflow_id)
            if workflow is not None:
                workflow.status = WorkflowStatus.WAITING_FOR_USER
                workflow.updated_at = datetime.now(timezone.utc)
                self.workflow_repo.update(workflow)

    async def _on_workflow_resumed(self, event: Event) -> None:
        step_id = event.payload.get("step_id")
        action = event.payload.get("action", "retry")
        logger.info("WORKFLOW_RESUMED workflow=%s step=%s action=%s", event.workflow_id, step_id, action)
        if step_id and self.has_graph(event.workflow_id):
            await self.resume_step(event.workflow_id, step_id, action=action)
            return

        # Workflow-level gate (e.g. EligibilityAgent's block_workflow) has
        # no specific step to unpause -- just resume forward progress.
        if self.has_graph(event.workflow_id):
            graph = self.get_graph(event.workflow_id)
            claimed = graph.claim_ready_steps()
            self._sync_workflow_from_graph(event.workflow_id, force_status=WorkflowStatus.RUNNING)
            if claimed:
                await self._record_and_publish(
                    Event(
                        workflow_id=event.workflow_id,
                        event_type=EventType.NEXT_ACTION_TRIGGERED,
                        payload={"ready_steps": [s.id for s in claimed]},
                        source_agent="workflow_engine",
                    )
                )

    async def _on_workflow_completed(self, event: Event) -> None:
        logger.info("WORKFLOW_COMPLETED workflow=%s", event.workflow_id)

    async def _on_workflow_failed(self, event: Event) -> None:
        logger.info("WORKFLOW_FAILED workflow=%s payload=%s", event.workflow_id, event.payload)

    # Backwards-compatible alias for the Part 1 name.
    register_placeholder_handlers = register_core_handlers
