from enum import Enum


class WorkflowStatus(str, Enum):
    RUNNING = "RUNNING"
    WAITING_FOR_USER = "WAITING_FOR_USER"
    BLOCKED = "BLOCKED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class StepStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    WAITING = "WAITING"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"


class ApplicationStatus(str, Enum):
    SUBMITTED = "SUBMITTED"
    PENDING = "PENDING"
    DOCUMENT_MISSING = "DOCUMENT_MISSING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"


class EventType(str, Enum):
    USER_REQUEST_CREATED = "USER_REQUEST_CREATED"
    GOAL_ANALYZED = "GOAL_ANALYZED"
    WORKFLOW_CREATED = "WORKFLOW_CREATED"
    REQUIREMENTS_IDENTIFIED = "REQUIREMENTS_IDENTIFIED"
    ELIGIBILITY_CHECKED = "ELIGIBILITY_CHECKED"
    DOCUMENTS_VALIDATED = "DOCUMENTS_VALIDATED"
    APPLICATION_READY = "APPLICATION_READY"
    APPLICATION_SUBMITTED = "APPLICATION_SUBMITTED"
    APPLICATION_STATUS_CHANGED = "APPLICATION_STATUS_CHANGED"
    DOCUMENT_MISSING = "DOCUMENT_MISSING"
    APPLICATION_APPROVED = "APPLICATION_APPROVED"
    APPLICATION_REJECTED = "APPLICATION_REJECTED"
    NEXT_ACTION_TRIGGERED = "NEXT_ACTION_TRIGGERED"
    USER_ACTION_REQUIRED = "USER_ACTION_REQUIRED"
    WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"
    WORKFLOW_FAILED = "WORKFLOW_FAILED"
    # Added in Part 2 for the human-in-the-loop gate: published (by a future
    # Part 3 API route) to unblock a WAITING_FOR_USER/BLOCKED workflow.
    WORKFLOW_RESUMED = "WORKFLOW_RESUMED"
